# Spring properties
spring:
  application:
    name: student-management-system
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    
# Mongo properties
  data:
    mongodb:
      host: @mongo.host@
      port: @mongo.port@
      database: @mongo.database@


# HTTP Server
server:
  port: @http.port@ # HTTP (Tomcat) port
